version: '3.8'

services:
  postgres:
    image: postgres:14.2
    ports:
      - 5432:5432
    restart: always

  odoo-15:
    image: odoo:15.0
    ports:
      - 8069:8069
    volumes:
      - odoo-15-data:/var/lib/odoo
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always

  odoo-16:
    image: odoo:16.0
    ports:
      - 8071:8069
    volumes:
      - odoo-16-data:/var/lib/odoo
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    restart: always
