version: '3'
services:
  web:
    image: odoo:15
    depends_on:
      - db_instance1
    environment:
      ODOO_DB_HOST: db_instance1
      ODOO_DB_PORT: 5432
      ODOO_DB_USER: odoo_user1
      ODOO_DB_PASSWORD: odoo_password1
    ports:
      - "8069:8069"
    networks:
      - odoo_network1

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: db_instance1
      POSTGRES_USER: odoo_user1
      POSTGRES_PASSWORD: odoo_password1


networks:
  odoo_network1:
